{{- /*
  We first check if namespaces are defined as a map.  If it is we call
  our helper function in _helpers.tpl to process the namespaces
  described in the values file. This is to support issue 
  https://github.com/validatedpatterns/common/issues/459 created by our customer.
*/ -}}
{{- if kindIs "map" .Values.clusterGroup.namespaces }}
{{- template "clustergroup.template.core.namespaces.map" (list .Values.clusterGroup.namespaces $.Values.global.pattern $.Values.clusterGroup.name) }}
{{- else }}
{{- range $ns := .Values.clusterGroup.namespaces }}
{{- if $ns }} {{- /* Skip null namespaces */}}
{{- $disabled := false }}
{{- if kindIs "map" $ns }}
  {{- range $k, $v := $ns }}{{- /* We loop here even though the map has always just one key */}}
    {{- $disabled = $v.disabled | default false }}
  {{- end }}
{{- end }}
{{- if $disabled }} {{- /* This allows us to null out a Namespace entry by specifying disabled: true in an override file */}}
{{- else }}
---
apiVersion: v1
kind: Namespace
metadata:
  {{- if kindIs "map" $ns }}
  {{- range $k, $v := $ns }}{{- /* We loop here even though the map has always just one key */}}
  name: {{ $k }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
    {{- if $v.labels }}
    {{- range $key, $value := $v.labels }} {{- /* We loop here even though the map has always just one key */}}
    {{ $key }}: {{ $value | default "" | quote }}
    {{- end }}
    {{- end }}
  {{- include "clustergroup.annotations" $v.annotations | nindent 2 }}
  {{- end }}{{- /* range $k, $v := $ns */}}

  {{- else if kindIs "string" $ns }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
  name: {{ $ns }}
  {{- end }} {{- /* if kindIs "string" $ns */}}
spec:
{{- end }}{{- /* if $disabled */}}
{{- end }}{{- /* if $ns (skip null namespaces) */}}
{{- end }}
{{- end }}
