# WARNING: ONLY USE THIS FOR MANAGING CLUSTERS NOT FOR REGULAR USERS
# This CRB is also pre-created by the ACM policy (application-policies.yaml)
# on managed clusters to ensure the ArgoCD controller has cluster-admin
# before the first sync. It's kept here for non-ACM deployments.
# See the commit messages around this change for a full explanation
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.global.vpArgoNamespace }}-cluster-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.global.vpArgoNamespace }}-argocd-application-controller
    namespace: {{ $.Values.global.vpArgoNamespace }}
  # NOTE: THIS MUST BE FIXED FOR MULTITENANT SETUP
  - kind: ServiceAccount
    name: {{ $.Values.global.vpArgoNamespace }}-argocd-server
    namespace: {{ $.Values.global.vpArgoNamespace }}
---
# WARNING: ONLY USE THIS FOR MANAGING CLUSTERS NOT FOR REGULAR USERS
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}-cluster-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    # This is the {ArgoCD.name}-argocd-application-controller
    name: {{ .Values.clusterGroup.name }}-gitops-argocd-application-controller
    namespace: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}
  # NOTE: THIS MUST BE FIXED FOR MULTITENANT SETUP
  - kind: ServiceAccount
    # This is the {ArgoCD.name}-argocd-server
    name: {{ .Values.clusterGroup.name }}-gitops-argocd-server
    namespace: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}
  # NOTE: This is needed starting with gitops-1.5.0 (see issue common#76)
  - kind: ServiceAccount
    name: {{ .Values.clusterGroup.name }}-gitops-argocd-dex-server
    namespace: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}
